version: 3
server:
  addr: :80
  url: https://cal.julian-lemmerich.de
  litemode: false
  loglevel: debug
  imprintlink: ""
  privacypolicylink: ""
  db:
    host: postgres
    db-name: ical_relay
    user: dbuser
    password: password
  super-tokens:
    - "supersecret"
