services:
  ical-notifier:
    image: ical-notifier:test
    command: /usr/bin/ical-notifier --superverbose --config /etc/ical-relay/config.yml
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./config.yml:/etc/ical-relay/config.yml:ro
      - ./data.yml:/etc/ical-relay/data.yml:ro
      - ../../testdata/basic.ics:/etc/ical-relay/notifystore/test-past.ics:ro
      - ./test_changed.ics:/etc/ical-relay/test_changed.ics:ro
    depends_on:
      mockhook:
        condition: service_started
  mockhook:
    build:
      context: .
      dockerfile_inline: |
        FROM php:apache
        RUN echo -e "<?php file_put_contents('body.json', file_get_contents('php://input')); ?>" >> /var/www/html/webhook.php
