builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - 386
archives:
- replacements:
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: deb
    package_name: ical-relay
    homepage: https://github.com/Thor77/ical-relay
    maintainer: Thor77 <thor77 at thor77 dot org>
    description: Test
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    files:
      'misc/ical-relay.service': '/lib/systemd/system/ical-relay.service'
    config_files:
      'config.toml': '/etc/ical-relay.toml'
    scripts:
      postinstall: 'misc/postinstall.sh'
