version: 2
server:
    addr: :8080
    url: https://localhost
    loglevel: trace
    storagepath: .
    templatepath: ./templates/
    imprintlink: ""
    privacypolicylink: ""
profiles:
    test:
        sources:
            - "https://vorlesungsplan.stuvma.de/profiles/TINF21%20CS1"
        public: false
        immutable-past: true
        admin-tokens: []
