url = "https://gitlab.com/p-fruck/dhbw-ical-fix/-/jobs/artifacts/master/raw/ical/8321001.ical?job=update_calendar"

[server]
addr = ":8080"
loglevel = "debug"

[profiles]
    [profiles.relay]
    regex = ["20210902T085552Z-296867001@group-e.dhbw-mannheim.de"]
    public = true
    from = "2021-12-02T00:00:00Z"
    until = "2021-12-31T00:00:00Z"
    passid = true
