version: '3'

services:
  ical-relay:
    build:
      context: .
      dockerfile: ./cmd/ical-relay/Dockerfile
    command: /usr/bin/ical-relay --config /etc/ical-relay/config.yml --import-data
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./cmd/ical-relay/config.yml:/etc/ical-relay/config.yml
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ical_relay
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "ical_relay"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
