version: '3'

services:
  ical-relay:
    build:
      context: .
      dockerfile: ./cmd/ical-relay/Dockerfile
    command: /usr/bin/ical-relay --config /etc/ical-relay/config.yml --import-data /etc/ical-relay/data.yml
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./cmd/ical-relay/config.yml:/etc/ical-relay/config.yml
      - ./cmd/ical-relay/data.yml:/etc/ical-relay/data.yml
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
  
  ical-notifier:
    build:
      context: .
      dockerfile: ./cmd/ical-notifier/Dockerfile
    volumes:
      - ./cmd/ical-notifier/notifier-config.yml:/etc/ical-relay/notifier-config.yml
    depends_on:
      ical-relay:
        condition: service_healthy
    restart: on-failure
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ical_relay
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "su", "-", "postgres", "pg_isready", "-d", "ical_relay"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
