services:
  ical-relay:
    image: ical-relay:test
    command: /usr/bin/ical-relay --verbose --config /etc/ical-relay/relay-config.yml --import-data /etc/ical-relay/data.yml
    volumes:
      - ./relay-config.yml:/etc/ical-relay/relay-config.yml:ro
      - ./data.yml:/etc/ical-relay/data.yml:ro
      - ./test_changed.ics:/etc/ical-relay/test_changed.ics:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ical_relay
    healthcheck:
      test: ["CMD-SHELL", "su", "-", "postgres", "pg_isready", "-d", "ical_relay"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  
  ical-notifier:
    image: ical-notifier:test
    command: /usr/bin/ical-notifier --superverbose --config /etc/ical-relay/notifier-config.yml
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./notifier-config.yml:/etc/ical-relay/notifier-config.yml:ro
      - ../../testdata/basic.ics:/etc/ical-relay/notifystore/test-past.ics:ro
    depends_on:
      ical-relay:
        condition: service_healthy
      mockmail:
        condition: service_started
  mockmail:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:12
        RUN apt update && apt install -y postfix
        RUN postconf -e 'maillog_file=/var/log/mail.log'
        RUN postconf -F '*/*/chroot = n'
        RUN postconf -e 'mydestination=static:all'
        RUN postconf -e 'smtpd_tls_security_level=none'
        CMD postfix start && tail -f /var/log/mail.log
