notifiers:
  test:
    source: "base64://QkVHSU46VkNBTEVOREFSClZFUlNJT046Mi4wCkNBTFNDQUxFOkdSRUdPUklBTgpCRUdJTjpWRVZFTlQKU1VNTUFSWTpBY2Nlc3MtQS1SaWRlIFBpY2t1cApEVFNUQVJUOjIwMjQwODAyVDEwMzQwMApEVEVORDoyMDI0MDgwMlQxMTA0MDAKTE9DQVRJT046RnJhbmtmdXJ0CkVORDpWRVZFTlQKQkVHSU46VkVWRU5UClNVTU1BUlk6RXZlbnQyCkRUU1RBUlQ6MjAyNDA4MjlUMjE1MgpEVEVORDoyMDI0MDgyOVQyMjAwCkxPQ0FUSU9OOkhhbWJ1cmcKRU5EOlZFVkVOVApFTkQ6VkNBTEVOREFS"
    recipients:
      - type: "mail"
        recipient: "root@mockmail"
