openapi: 3.0.3
info:
  title: ical-relay
  description: |-
    ...
  contact:
    email: mail@julian-lemmerich.de
  license:
    name:  GNU GENERAL PUBLIC LICENSE
    url: https://www.gnu.org/licenses/gpl-3.0.html
  version: 2.0.0-beta
externalDocs:
  description: Find out more about ical-relay
  url: https://www.github.com/jm-lemmi/ical-relay
#servers:
#  - url: https://cal.julian-lemmerich.de/
tags:
  - name: public
    description: Everything availible publicly
  - name: admin
    description: Access to Edit Relay-Profiles
paths:
  /api/profiles:
    get:
      tags:
        - public
      summary: Get all public calendars
      description: List all public calendars with their URL.
      operationId: listCalendars
      responses:
        '200':
          description: Successful operation
          #content:
          #  application/json:
          #    schema:
          #      $ref: '#/components/schemas/Pet'
        '500':
          description: Either Error, or calendar not found
  /api/reloadconfig:
    get:
      tags:
        - public
      summary: Reloads the config
      description: Reloads the config of the relay stored on the server.
      operationId: reloadConfig
      responses:
        '200':
          description: successful operation
        '500':
          description: Server Error
  /api/notifiers/{notifier}/recipient:
    post:
      tags:
        - public
      summary: Adds an E-Mail-Recipient to a Notifier
      description: ''
      operationId: addRecipient
      parameters:
        - name: notifier
          in: path
          description: Name of Notifier to add to
          required: true
          schema:
            type: string
        - name: mail
          in: query
          description: E-Mail Address that will be added
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: not a valid E-Mail address
        '404':
          description: Notifier does not exist
        '500':
          description: Server Error
    delete:
      tags:
        - public
      summary: Removes an E-Mail-Recipient from a Notifier
      description: ''
      operationId: rmRecipient
      parameters:
        - name: notifier
          in: path
          description: Name of Notifier to add to
          required: true
          schema:
            type: string
        - name: mail
          in: query
          description: E-Mail Address that will be removed
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: not a valid E-Mail address
        '404':
          description: Notifier does not exist
        '500':
          description: Server Error
  /api/profiles/{profile}/checkAuth:
    get:
      tags:
        - admin
      summary: Checks Token Autorization
      description: Checks if token is authorized to access the profile.
      operationId: checkAuth
      parameters:
        - name: profile
          in: path
          description: Name of Profile to check Auth for.
          required: true
          schema:
            type: string
      security:
        - tokenAuth: []
      responses:
        '200':
          description: Authentication successful
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
  /api/profiles/{profile}/modules:
    get:
      tags:
        - admin
      summary: Get all Modules of a Profile
      description: Get all Modules of a Profile
      operationId: getModules
      parameters:
        - name: profile
          in: path
          description: Name of Profile to get Modules for.
          required: true
          schema:
            type: string
      security:
        - tokenAuth: []
      responses:
        '200':
          description: successful operation
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
        '500':
          description: Server Error
    post:
      tags:
        - admin
      summary: Add a Module to a Profile
      description: General add any Module to a Profile
      operationId: addModule
      parameters:
        - name: profile
          in: path
          description: Name of Profile to add Module to.
          required: true
          schema:
            type: string
        # json body with module information, will be piped directly into the config
      security:
        - superAuth: []
      responses:
        '200':
          description: successful operation
        '400':
          description: Module not found
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
        '500':
          description: Server Error
  /api/profiles/{profile}/calentry:
    get:
      tags:
        - public
      summary: Get specific Calendar Entry
      description: Get specific Calendar Entry. Probably useless, but maybe for error checking afterwards?
      operationId: getCalEntry
      parameters:
        - name: profile
          in: path
          description: Name of Profile to get CalEntries for.
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: ID of Entry to get
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: ID not found
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
        '500':
          description: Server Error
    post:
      tags:
        - admin
      summary: Edit a Calendar Entry
      description: Edit a Calendar Entry
      operationId: editCalEntry
      parameters:
        - name: profile
          in: path
          description: Name of Profile to add CalEntry to.
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: ID of Entry to edit
          required: true
          schema:
            type: string
        # json body with changed entry information. Will be parsed and calls the editing functions to add specific modules.
      security:
        - tokenAuth: []
      responses:
        '200':
          description: successful operation
        '400':
          description: ID not found
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
        '500':
          description: Server Error
    put:
      tags:
        - admin
      summary: Add a Calendar Entry
      description: Add a Calendar Entry
      operationId: addCalEntry
      parameters:
        - name: profile
          in: path
          description: Name of Profile to add CalEntry to.
          required: true
          schema:
            type: string
        # json body with entry information. Will be parsed to ics file with add-ics function
      security:
        - tokenAuth: []
      responses:
        '200':
          description: successful operation
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
        '500':
          description: Server Error
    delete:
      tags:
        - admin
      summary: Delete a Calendar Entry
      description: Delete a Calendar Entry
      operationId: rmCalEntry
      parameters:
        - name: profile
          in: path
          description: Name of Profile to add CalEntry to.
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: ID of Entry to delete
          required: true
          schema:
            type: string
      security:
        - tokenAuth: []
      responses:
        '200':
          description: successful operation
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
        '500':
          description: Server Error
  /api/profiles/{profile}/uploadICS:
    post:
      tags:
        - admin
      summary: Upload ICS File
      description: Upload ICS File, which will be added to profile in full.
      operationId: uploadICS
      consumes:
         - multipart/form-data
      parameters:
        - name: profile
          in: path
          description: Name of Profile to add CalEntry to.
          required: true
          schema:
            type: string
        - name: upfile
          in: formData
          type: file
          description: The file to upload
      security:
        - tokenAuth: []
      responses:
        '200':
          description: successful operation
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Profile not found
        '500':
          description: Server Error

components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token Authentication for specific profiles. Not all features availible.
    superAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token Authentication for all profiles and Server features. All features availible.

  responses:
    UnauthorizedError:
      description: Token is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
