name: Compile

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.0' # The Go version to download (if necessary) and use.
      - run: go generate cmd/ical-relay/main.go
      - run: go build -o ./bin/ical-relay ./cmd/ical-relay/
      - uses: actions/upload-artifact@v3
        with:
          name: ical-relay
          path: ./bin/ical-relay

  Package-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          file: ./cmd/ical-relay/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: false # Will only build if this is not here