name: Compile Binary

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:
    tags:
      - v*

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0' # The Go version to download (if necessary) and use.
      - run: go build .
      - uses: actions/upload-artifact@v3
        with:
          name: ical-relay
          path: ./ical-relay

  Package:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Create debpkg structure
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/etc/ical-relay
          cp config.yml.example .debpkg/etc/ical-relay/

          mkdir -p .debpkg/DEBIAN
          cp misc/postinstall.sh .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
          cp misc/ical-relay.service .debpkg/etc/systemd/system/ical-relay.service
      - name: Download binary
        uses: actions/download-artifact@v3
        id: download
        with:
          name: ical-relay
      - run: |
          cp ${{steps.download.outputs.download-path}}/ical-relay .debpkg/usr/bin/
          chmod +x .debpkg/usr/bin/ical-relay
      - uses: jiro4989/build-deb-action@v2
        id: package
        with:
          package: ical-relay
          package_root: .debpkg
          maintainer: Julian Lemmerich <mail@julian-lemmerich.de>
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          desc: 'Relay ical urls and edit them on the fly with different modules.'
      - uses: actions/upload-artifact@v3
        with:
          name: ical-relay.deb
          path: ./${{steps.package.outputs.file_name}}
