name: Package .deb

on:
  workflow_run:
    workflows: ["Compile Binary"]
    types: 
      - completed

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Create debpkg structure
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/etc/ical-relay
          cp config.yml.example .debpkg/etc/ical-relay/

          mkdir -p .debpkg/DEBIAN
          cp misc/postinstall.sh .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
          cp misc/ical-relay.service .debpkg/DEBIAN/ical-relay.service
      - uses: actions/download-artifact@v3
        with:
          name: ical-relay
      - run: |
          cp ${{steps.download.outputs.download-path}} .debpkg/usr/bin/
          chmod +x .debpkg/usr/bin/ical-relay
      - uses: jiro4989/build-deb-action@v2
        with:
          package: ical-relay
          package_root: .debpkg
          maintainer: Julian Lemmerich <mail@julian-lemmerich.de>
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          desc: 'Relay ical urls and edit them on the fly with different modules.'
