name: Test

on:
  push:
  pull_request:

jobs:
  tzgenerate:
    uses: ./.github/workflows/generate-timezones.yml
  go-test:
    needs: tzgenerate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - run: go generate cmd/ical-relay/main.go

      - name: Run tests
        run: go test ./cmd/ical-relay/...
  
  system-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests
        run: cd ./.github/sys-tests/; ./tests.sh
